<?php


/**
 * Implements hook_permission().
 *
 * @return type
 */
function finurlig_create_permission() {
  return array(
    'create finurlig fact' => array(
      'title' => t('Administer my module'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function finurlig_create_menu() {
  $items = array();

  // Menu callback used to get the login form as a JSON encoded array.
  $items['ajax/create/fact'] = array(
    'title' => 'Create new fact',
    'description' => 'Create a new fact via AJAX',
    'page callback' => 'finurlig_create_fact',
    'page arguments' => array(),
    'access arguments' => array('create finurlig fact'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Callback that returns the create fact node form as JSONP.
 */
function finurlig_create_fact() {
  $form_id = 'finurlig_crate_fact_form';

  // Get user login form.
  $form = drupal_get_form($form_id);
  echo render($form);
  exit();
}

/**
 * Implements the create fact form, which can be used to load the form into an
 * iframe on a remote site and thereby create facts (nodes).
 */
function finurlig_crate_fact_form() {
  $form = array();

  $form['title'] = array (
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#attribute' => array('placeholder' => 'test'),
  );

  $form['author'] = array (
    '#type' => 'textfield',
    '#title' => t('Author'),
  );

  $form['fact'] = array(
    '#type' => 'textarea',
    '#title' => t('Fact'),
  );

  $form['inspiration'] = array(
    '#type' => 'fieldset',
    '#title' => t('Inspiration'),
  );

  $form['inspiration']['inspiration_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
  );

  $form['inspiration']['inspiration_link'] = array(
    '#type' => 'textfield',
    '#title' => t('link'),
  );

  $form['source'] = array(
    '#type' => 'fieldset',
    '#title' => t('Source'),
  );

  $form['source']['source_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
  );

  $form['source']['source_link'] = array(
    '#type' => 'textfield',
    '#title' => t('link'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create'),
  );

  $form['#validate'][] = 'finurlig_crate_fact_form_validate';

  return $form;
}

function finurlig_crate_fact_form_validate($form, $form_state) {
  $values = $form_state['values'];

  // Create a basic node that can hold the fact information submitted in the
  // form.
  $node = new stdClass();
  $node->type = 'fact';
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;

  // Title.
  $node->title = $values['title'];

  // Content
  $node->field_fact_content[$node->language][0]['value'] = $values['fact'];
  $node->field_fact_content[$node->language][0]['format'] = 'editor_html';

  // Inspiration.
  $node->field_fact_inspiration[$node->language][0] = array(
    'url' => $values['inspiration_link'],
    'title' => $values['inspiration_title'],
    'attributes' => array(
      'rel' => 'external',
      'target' => '_blank',
    ),
    'display_url' => $values['inspiration_link'],
    'html' => 1,
  );

  // Source.
  $node->field_fact_source[$node->language][0] = array(
    'url' => $values['source_link'],
    'title' => $values['source_title'],
    'attributes' => array(
      'rel' => 'external',
      'target' => '_blank',
    ),
    'display_url' => $values['source_link'],
    'html' => 1,
  );

  // Author.
  $node->field_fact_author[$node->language][0] = array(
    'value' => $values['author'],
    'format' => '',
    'safe_value' => check_plain($values['author']),
  );

  // Organization.
  $node->field_fact_organization[$node->language][0] = array(
    'value' => '',
    'format' => '',
    'safe_value' => '',
  );

  // Save the node.
  node_save($node);

  /**
   * @todo: Return better information that can be used to take action (JSON ?).
   */
  echo t('The fact have been created');
  exit();
}